Cynara_zkthon
Polygon-Advocates/zkThon-challenges pull request #132
Opened 2023-03-27 21:17 UTC by Cynaral

## Description

This pull request is for the zkEVM Challenge 1,2. I have reviewed the zkEVM documentation and shared my understanding through a Twitter thread using the hashtags #zkThon and #zkEVM. The link to my Twitter thread is https://twitter.com/cynara2007/status/1640021799445438465?s=20

## Checklist

- [ ] I have created a new file named `solution-1.md,solution-2.md` for this challenge.
- [ ] I have added the details of my submission to the [Airtable form](https://airtable.com/shr21z0FfPImZfYBQ).
- [ ] I have named my branch `Cynara_zkthon`.

2023-03-30 08:52 UTC, megabyte0x requested changes

2023-03-30 08:52 UTC, megabyte0x commented on solution-2.md
Please add the deployed contract link to the file.

Thanks 😄

2023-03-30 09:09 UTC, Cynaral commented on solution-2.md
ok) done

2023-03-31 05:12 UTC, megabyte0x commented on solution-2.md
Good work 🔥

2023-03-31 05:13 UTC, megabyte0x requested changes

2023-03-31 05:13 UTC, megabyte0x commented on solution-3.md
Please add the interface code used to interact with the contract. 

Thanks

2023-03-31 19:28 UTC, closed without merging