Create solution-1.md
Polygon-Advocates/zkThon-challenges pull request #76
Opened 2023-03-26 15:51 UTC by akashbiswas0

## Description

This pull request is for the zkEVM Challenge 1. I have reviewed the zkEVM documentation and shared my understanding through a Twitter thread using the hashtags #zkThon and #zkEVM. The link to my Twitter thread is [https://twitter.com/akashbtwts/status/1640013777948266496?s=20].

## Checklist

- [ ] I have created a new file named `solution-1.md` for this challenge.
- [ ] I have added the details of my submission to the [Airtable form](https://airtable.com/shr21z0FfPImZfYBQ).
- [ ] I have named my branch `username_zkthon`.

2023-03-26 17:53 UTC, PriyathamVarma approved these changes
Thank you for the participation ser

2023-03-30 17:59 UTC, megabyte0x requested changes

2023-03-30 17:59 UTC, megabyte0x commented on solution-2.md
Please include the deployed contract link in the file.

Thanks

2023-03-30 18:36 UTC, akashbiswas0 commented on solution-2.md
added please review and add label

2023-12-24 20:03 UTC, closed without merging